import java.awt.*;
import java.awt.event.*;

import javax.swing.*;
import javax.swing.border.*; 

import org.omg.CORBA.portable.CustomValue;

import java.sql.*;


/*
 * CustomerController is a control class that handles action events on the Clerk menu.
 * It updates the GUI based on which menu item the clerk selected and also use methods
 * in CustomerModel to update the tables in database
 */

public class CustomerController implements ActionListener, ExceptionListener {

	private ShopGUI shopGUI = null;
	private CustomerModel customerModel = null;
	
	public CustomerController(ShopGUI sg) {
		shopGUI = sg;
		customerModel = new CustomerModel();
		// add this to the listener list of the customer model
		customerModel.addExceptionListener(this);
	}
	
	
	/**
	 * generate a dialog to allow the customer to search items
	 *
	 */
	class SearchItemDialog extends JDialog implements ActionListener {
		
		// we take shopGUI as a parameter because we want the error message 
		// generated by this dialog to be shown in the status area of the main GUI
		public SearchItemDialog(ShopGUI shopGUI) {
			// TODO
		}
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			
		}
		
	}
	
	
	/**
	 * generate a dialog to allow the customer to add item to the shopping cart
	 *
	 */
	class AddItemToCartDialog extends JDialog implements ActionListener {

		public AddItemToCartDialog(ShopGUI shopGUI) {
			// TODO
		}
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			
		}
		
	}

	/**
	 * generate a dialog to allow the customer to remove item to the shopping cart
	 *
	 */
	class RemoveItemDialog extends JDialog implements ActionListener {

		public RemoveItemDialog(ShopGUI shopGUI) {
			// TODO
		}
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			
		}
		
	}

	/**
	 * generate a dialog to allow the customer to register
	 *
	 */
	class RegistrationDialog extends JDialog implements ActionListener {

		public RegistrationDialog(ShopGUI shopGUI) {
			// TODO
		}
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			
		}
		
	}

	/**
	 * generate a dialog to allow the customer to checkout and pay by credit card
	 *
	 */
	class CheckOutDialog extends JDialog implements ActionListener {

		public CheckOutDialog(ShopGUI shopGUI) {
			// TODO
		}
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			
		}
		
	}
	
	
	@Override
	public void exceptionGenerated(ExceptionEvent ex) {
		// TODO Auto-generated method stub
		
	}

	
	/*
	 * This event handler gets called when the user selects a menu item
	 */ 
	@Override
	public void actionPerformed(ActionEvent e) {
		String actionCommand = e.getActionCommand();

		// you cannot use == for string comparisons
		if (actionCommand.equals(ShopGUI.REGISTRATION)) {
			//TODO
			return;
		} else if (actionCommand.equals(ShopGUI.SEARCH_ITEM)) {
			SearchItemDialog searchItemDialog = new SearchItemDialog(shopGUI);
			searchItemDialog.pack();
			//mvb.centerWindow(iDialog);
			searchItemDialog.setVisible(true);
			return; 
		} else if (actionCommand.equals(ShopGUI.ADD_ITEM_TO_CART)) {
			// TODO
			return;
		} else if (actionCommand.equals(ShopGUI.REMOVE_ITEM)) {
			// TODO
			return;
		} else if (actionCommand.equals(ShopGUI.CHECK_OUT)) {
			// TODO
			return;
		}
	}
	
}